# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='category_photos')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='product_photos')),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ingredients',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='product_photos')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='db.Category')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Product')),
            ],
            options={
                'verbose_name': 'Product Ingredients',
                'verbose_name_plural': 'Product Ingredients',
                'db_table': 'product_ingredients',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Units',
                'verbose_name_plural': 'Units',
                'db_table': 'unit',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productingredients',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='db.ProductIngredients', to='db.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Unit'),
        ),
    ]
