# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredients',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='db.Unit'),
            preserve_default=False,
        ),
    ]
