# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 19:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Title')),
                ('header', models.TextField(verbose_name='Card Article Preview')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Unique Article Identifier')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='article_images/', verbose_name='Article Image')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian')], default='uk', max_length=20, verbose_name='Language')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Article Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes Count')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'vincent_articles',
                'ordering': ('-created_at',),
            },
        ),
    ]
