# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('place_qty', models.IntegerField(default=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wish', models.TextField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableBooking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'table_booking',
                'ordering': ('-created_at',),
            },
        ),
    ]
