# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 15:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20171021_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\Study\\4_Course(1)\\ControlTheory\\Project\\Project\\static'), upload_to='category_photos'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\Study\\4_Course(1)\\ControlTheory\\Project\\Project\\static'), upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\Study\\4_Course(1)\\ControlTheory\\Project\\Project\\static'), upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
